# Generated by Django 3.0.2 on 2020-02-08 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0003_auto_20200208_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='faction',
            field=models.CharField(default='none', max_length=20, verbose_name='Faction'),
            preserve_default=False,
        ),
    ]
