# Generated by Django 3.0.2 on 2020-02-09 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0004_player_faction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='victory_points',
        ),
    ]
