# Generated by Django 3.0.2 on 2020-02-09 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0001_initial'),
        ('map', '0006_territory_description'),
        ('player', '0005_remove_player_victory_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='campaign_points',
            field=models.IntegerField(default=0, verbose_name='Campaign Points'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='challenge_location',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='map.Territory', verbose_name='Challenge Location'),
        ),
        migrations.AddField(
            model_name='player',
            name='event',
            field=models.CharField(blank=True, choices=[('raid', 'Raid Supply Lines'), ('construction', 'Forward Construction'), ('storm', 'Warp Storm'), ('orders', 'Issue Special Orders'), ('recon', 'Reconnaissandce'), ('diplomacy', 'Aggressive Diplomacy'), ('colonization', 'Prioritize Colonization'), ('special_forces', 'Enlist Special Forces'), ('drill', 'Drill the Soldiers'), ('train', 'Train the Leaders')], max_length=15, null=True, unique=True, verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='player',
            name='event_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_targeter', to='player.Player', verbose_name='Event Target'),
        ),
        migrations.AddField(
            model_name='player',
            name='opponent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='challenger', to='player.Player', verbose_name='Opponent'),
        ),
        migrations.AddField(
            model_name='player',
            name='reconnaissance_subterfuge_mission',
            field=models.CharField(blank=True, choices=[('sabatoge', 'Sabatoge Fortifications'), ('rescue', 'Rescue Prisoners'), ('seize', 'Seize Ground'), ('disrupt', 'Disrupt Supplies'), ('ambush', 'Ambush'), ('feint', 'Feint'), ('assassinate', 'Assassinate'), ('take_prisoners', 'Take Prisoners'), ('root_out', 'Root Out Enemy Agents'), ('intelligence', 'Seek Intelligence'), ('terror', 'Terror Tactics')], max_length=20, null=True, verbose_name='Subterfuge Mission'),
        ),
        migrations.AddField(
            model_name='player',
            name='reconnaissance_subterfuge_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconnaissance_subterfuge_targeter', to='player.Player', verbose_name='Subterfuge Target'),
        ),
        migrations.AddField(
            model_name='player',
            name='subterfuge_mission',
            field=models.CharField(blank=True, choices=[('sabatoge', 'Sabatoge Fortifications'), ('rescue', 'Rescue Prisoners'), ('seize', 'Seize Ground'), ('disrupt', 'Disrupt Supplies'), ('ambush', 'Ambush'), ('feint', 'Feint'), ('assassinate', 'Assassinate'), ('take_prisoners', 'Take Prisoners'), ('root_out', 'Root Out Enemy Agents'), ('intelligence', 'Seek Intelligence'), ('terror', 'Terror Tactics')], max_length=20, null=True, verbose_name='Subterfuge Mission'),
        ),
        migrations.AddField(
            model_name='player',
            name='subterfuge_target',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subterfuge_targeter', to='player.Player', verbose_name='Subterfuge Target'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('subterfuge_mission', 'reconnaissance_subterfuge_mission', 'reconnaissance_subterfuge_target'), ('event', 'event_target'), ('subterfuge_mission', 'reconnaissance_subterfuge_mission', 'subterfuge_target'), ('reconnaissance_subterfuge_mission', 'reconnaissance_subterfuge_target'), ('game', 'user'), ('subterfuge_mission', 'subterfuge_target')},
        ),
    ]
