# Generated by Django 3.0.2 on 2020-03-14 00:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20200314_0017'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('player', '0007_auto_20200223_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='event',
            field=models.CharField(blank=True, choices=[('raid', 'Raid Supply Lines'), ('construction', 'Forward Construction'), ('storm', 'Warp Storm'), ('orders', 'Issue Special Orders'), ('recon', 'Reconnaissandce'), ('diplomacy', 'Aggressive Diplomacy'), ('colonization', 'Prioritize Colonization'), ('special_forces', 'Enlist Special Forces'), ('drill', 'Drill the Soldiers'), ('train', 'Train the Leaders')], max_length=15, null=True, verbose_name='Event'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('reconnaissance_subterfuge_mission', 'reconnaissance_subterfuge_target'), ('game', 'user'), ('subterfuge_mission', 'reconnaissance_subterfuge_mission', 'reconnaissance_subterfuge_target'), ('subterfuge_mission', 'reconnaissance_subterfuge_mission', 'subterfuge_target'), ('event', 'game'), ('subterfuge_mission', 'subterfuge_target'), ('event', 'event_target', 'game')},
        ),
    ]
