# Generated by Django 3.0.2 on 2020-02-04 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('roster', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='game.Game', verbose_name='Game')),
            ],
        ),
        migrations.CreateModel(
            name='Relic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relics', to='game.Game', verbose_name='Game')),
                ('holder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relic', to='roster.Unit', verbose_name='Holder')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relic', to='player.Player', verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='Territory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('feature', models.CharField(choices=[('industry', 'Industry'), ('fortification', 'Fortification'), ('critical_location', 'Critical Location')], max_length=30, verbose_name='feature')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='map.Planet', verbose_name='Planet')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='territories', to='player.Player', verbose_name='Player')),
            ],
            options={
                'unique_together': {('name', 'planet')},
            },
        ),
    ]
