# Generated by Django 3.0.2 on 2020-02-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='planet',
            unique_together={('game', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='relic',
            unique_together={('game', 'name')},
        ),
    ]
