# Generated by Django 3.0.2 on 2020-02-08 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('roster', '0004_auto_20200208_0645'),
        ('player', '0004_player_faction'),
        ('map', '0002_auto_20200208_0505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relic',
            name='holder',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relic', to='roster.Unit', verbose_name='Holder'),
        ),
        migrations.AlterField(
            model_name='relic',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relics', to='player.Player', verbose_name='Player'),
        ),
    ]
