# Generated by Django 3.0.2 on 2020-02-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_auto_20200208_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='relic',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Description'),
        ),
    ]
