# Generated by Django 3.0.2 on 2020-02-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_relic_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='feature',
            field=models.CharField(blank=True, choices=[('industry', 'Industry'), ('fortification', 'Fortification'), ('critical_location', 'Critical Location')], max_length=30, null=True, verbose_name='feature'),
        ),
    ]
