# Generated by Django 3.0.2 on 2020-02-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_auto_20200208_0807'),
    ]

    operations = [
        migrations.AddField(
            model_name='territory',
            name='description',
            field=models.CharField(blank=True, max_length=75, null=True, verbose_name='Description'),
        ),
    ]
