# Generated by Django 3.0.2 on 2020-02-04 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('player', '0001_initial'),
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KillTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Roster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Game', to='game.Game', verbose_name='Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.Player', verbose_name='Player')),
            ],
            options={
                'unique_together': {('player', 'game')},
            },
        ),
        migrations.CreateModel(
            name='KillTeamModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('datasheet', models.CharField(max_length=20, verbose_name='DataSheet')),
                ('wargear', models.CharField(blank=True, max_length=50, verbose_name='Wargear')),
                ('experiance', models.SmallIntegerField(verbose_name='Experiance')),
                ('specialism', models.CharField(blank=True, max_length=50, verbose_name='Specialism')),
                ('demeanor', models.CharField(blank=True, max_length=50, verbose_name='Demeanor')),
                ('dead', models.BooleanField(verbose_name='dead')),
                ('cost', models.SmallIntegerField(verbose_name='Cost')),
                ('killteam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='KillTeamModels', to='roster.KillTeam', verbose_name='Kill Team Model')),
            ],
        ),
        migrations.AddField(
            model_name='killteam',
            name='roster',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='KillTeam', to='roster.Roster', verbose_name='Roster'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Name')),
                ('datasheet', models.CharField(max_length=20, verbose_name='Datasheet')),
                ('wargear', models.CharField(blank=True, max_length=50, verbose_name='Wargear')),
                ('experiance', models.SmallIntegerField(verbose_name='Experiance')),
                ('battle_honors', models.CharField(blank=True, max_length=50, verbose_name='Battle Honors')),
                ('description', models.CharField(blank=True, max_length=50, verbose_name='Description')),
                ('warlord', models.BooleanField(verbose_name='Warlord')),
                ('dead', models.BooleanField(verbose_name='dead')),
                ('cost', models.SmallIntegerField(verbose_name='Cost')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Units', to='roster.Roster', verbose_name='Roster')),
            ],
            options={
                'unique_together': {('name', 'roster')},
            },
        ),
    ]
