# Generated by Django 3.0.2 on 2020-02-02 00:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roster', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='killteammodel',
            name='demeanor',
            field=models.CharField(blank=True, max_length=50, verbose_name='Demeanor'),
        ),
        migrations.AlterField(
            model_name='killteammodel',
            name='specialism',
            field=models.CharField(blank=True, max_length=50, verbose_name='Specialism'),
        ),
        migrations.AlterField(
            model_name='killteammodel',
            name='wargear',
            field=models.CharField(blank=True, max_length=50, verbose_name='Wargear'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='battle_honors',
            field=models.CharField(blank=True, max_length=50, verbose_name='Battle Honors'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='description',
            field=models.CharField(blank=True, max_length=50, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='wargear',
            field=models.CharField(blank=True, max_length=50, verbose_name='Wargear'),
        ),
        migrations.AlterUniqueTogether(
            name='roster',
            unique_together={('user', 'game')},
        ),
        migrations.RemoveField(
            model_name='roster',
            name='name',
        ),
    ]
