# Generated by Django 3.0.2 on 2020-02-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='test game 1', max_length=30, verbose_name='Name'),
            preserve_default=False,
        ),
    ]
